# .github/workflows/main.yml - Build and Test Workflow (Cleaned)
name: Build and Test Workflow

on:
  push:
    branches:
      - main # This workflow runs when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # Checks out your repository's code

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm # Path to the directory to cache
          # Corrected hashFiles key syntax
          key: "deps-node-modules-${{ hashFiles('package-lock.json') }}"

      - name: Install dependencies
        run: npm ci # Installs dependencies from package-lock.json

      - name: Build website
        run: npm run build # Builds your website for production

      - name: Upload artifacts
        uses: actions/upload-artifact@v4 # Using version 4
        with:
          name: dist-files # Name for the uploaded artifact
          path: dist # Path to the built files (relative to the working directory)
          if-no-files-found: warn # Warn if no files found, but don't fail job
          compression-level: 6
          overwrite: false
          include-hidden-files: false

  test:
    needs: build # This job will only run after the 'build' job completes successfully
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # Checks out your repository's code

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm # Path to the directory to cache
          # Corrected hashFiles key syntax
          key: "deps-node-modules-${{ hashFiles('package-lock.json') }}"

      - name: Install dependencies
        run: npm ci # Installs dependencies from package-lock.json

      - name: Lint code
        run: npm run lint # Runs your project's lint script

      - name: Test code
        run: npm run test # Runs your project's test script
