# .github/workflows/main.yml - Final Build, Test, and Deploy Workflow for React App
name: React App CI/CD

on:
  push:
    branches:
      - main # This workflow runs when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # Checks out your repository's code

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm # Path to the directory to cache
          # Corrected hashFiles key syntax for package-lock.json at root
          key: "deps-node-modules-${{ hashFiles('package-lock.json') }}"

      - name: Install dependencies
        run: npm ci # Installs dependencies from package-lock.json (based on package.json)

      - name: Build React App
        run: npm run build # Builds your React application for production (using Vite build script)

      - name: Upload built artifacts
        # This step is now using v4 to avoid deprecation warnings/failures
        uses: actions/upload-artifact@v4
        with:
          name: dist-files # Name for the uploaded artifact
          path: dist # Path to the built files (where Vite outputs, typically 'dist')
          if-no-files-found: warn # Warn if no files found, but don't fail job
          compression-level: 6
          overwrite: false
          include-hidden-files: false

  test:
    needs: build # This job will only run after the 'build' job completes successfully
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # Checks out your repository's code

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm # Path to the directory to cache
          # Corrected hashFiles key syntax for package-lock.json at root
          key: "deps-node-modules-${{ hashFiles('package-lock.json') }}"

      - name: Install dependencies
        run: npm ci # Installs dependencies from package-lock.json

      - name: Lint code
        run: npm run lint # Runs your project's lint script

      - name: Test code
        run: npm run test # Runs your project's test script

  deploy:
    # This job depends on both 'build' and 'test' jobs completing successfully.
    # We only deploy if both the build is successful and tests pass.
    needs: [build, test]
    runs-on: ubuntu-latest
    # Grant necessary permissions for GitHub Pages deployment
    permissions:
      contents: write # Allows the action to commit and push to the repository (e.g., to the gh-pages branch)
      pages: write    # Specifically allows the action to deploy to GitHub Pages
      id-token: write # Required for OIDC authentication, often used by GitHub Pages deployments
    steps:
      - name: Get code
        uses: actions/checkout@v3 # Checks out your repository's code

      - name: Download built artifacts
        # This step is now using v4
        uses: actions/download-artifact@v4
        with:
          name: dist-files # Name of the artifact to download
          path: dist # Path where the artifact will be downloaded (relative to the current working directory)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Action specifically designed for deploying to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Uses the default GITHUB_TOKEN provided by GitHub Actions
          publish_dir: ./dist # Specifies the directory to publish (where your built website is located)
          # Publish to the 'gh-pages' branch for project pages to avoid conflicts with 'main'.
          publish_branch: gh-pages
