# .github/workflows/main.yml - Simple Static Site Deployment Workflow
name: Static Site Deployment

on:
  push:
    branches:
      - main # This workflow runs when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    # THIS IS THE CRITICAL SECTION FOR PERMISSIONS
    # It grants the default GITHUB_TOKEN the necessary rights for GitHub Pages.
    permissions:
      contents: write # Allows the action to commit and push to the repository (e.g., to the gh-pages branch)
      pages: write    # Specifically allows the action to deploy to GitHub Pages
      id-token: write # Required for OIDC authentication, often used by GitHub Pages deployments
    steps:
      - name: Get code
        uses: actions/checkout@v3 # Checks out your repository's code

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Action specifically designed for deploying to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Uses the default GITHUB_TOKEN provided by GitHub Actions
          publish_dir: ./ # Specifies the directory to publish - assuming your static files are at the root
          publish_branch: gh-pages # Explicitly publish to the gh-pages branch (standard for project pages)
